version: '3.9'

services:
  db:
    image: mongo
    container_name: mongoBooking
    restart: always
    ports:
      - "27019:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234



